name: Semgrep

on:
  workflow_dispatch:

  # Scan all files on branches, block on any issues
  # push:
  #   branches: ["master", "main"]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Fetch project source
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets
            p/owasp-top-ten
            p/r2c-security-audit
            p/command-injection
            p/jwt
            p/xss
            p/insecure-transport
            p/nodejsscan
            p/nginx
            p/ci
        # Upload findings to GitHub Advanced Security Dashboard [step 1/2]
        # See also the next step.
          generateSarif: "1"
          
        # Upload findings to GitHub Advanced Security Dashboard [step 2/2]
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
          if: always()
